# Generated by Django 4.2.10 on 2024-03-05 18:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_alter_visit_options_visit_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='first_visit',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='destination',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
